//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for action-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="action-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="nothing"/>
 *     &lt;enumeration value="contact-source-site"/>
 *     &lt;enumeration value="contact-target-site"/>
 *     &lt;enumeration value="contact-sender"/>
 *     &lt;enumeration value="investigate"/>
 *     &lt;enumeration value="block-host"/>
 *     &lt;enumeration value="block-network"/>
 *     &lt;enumeration value="block-port"/>
 *     &lt;enumeration value="rate-limit-host"/>
 *     &lt;enumeration value="rate-limit-network"/>
 *     &lt;enumeration value="rate-limit-port"/>
 *     &lt;enumeration value="remediate-other"/>
 *     &lt;enumeration value="status-triage"/>
 *     &lt;enumeration value="status-new-info"/>
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="ext-value"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "action-type")
@XmlEnum
public enum ActionType {

    @XmlEnumValue("nothing")
    NOTHING("nothing"),
    @XmlEnumValue("contact-source-site")
    CONTACT_SOURCE_SITE("contact-source-site"),
    @XmlEnumValue("contact-target-site")
    CONTACT_TARGET_SITE("contact-target-site"),
    @XmlEnumValue("contact-sender")
    CONTACT_SENDER("contact-sender"),
    @XmlEnumValue("investigate")
    INVESTIGATE("investigate"),
    @XmlEnumValue("block-host")
    BLOCK_HOST("block-host"),
    @XmlEnumValue("block-network")
    BLOCK_NETWORK("block-network"),
    @XmlEnumValue("block-port")
    BLOCK_PORT("block-port"),
    @XmlEnumValue("rate-limit-host")
    RATE_LIMIT_HOST("rate-limit-host"),
    @XmlEnumValue("rate-limit-network")
    RATE_LIMIT_NETWORK("rate-limit-network"),
    @XmlEnumValue("rate-limit-port")
    RATE_LIMIT_PORT("rate-limit-port"),
    @XmlEnumValue("remediate-other")
    REMEDIATE_OTHER("remediate-other"),
    @XmlEnumValue("status-triage")
    STATUS_TRIAGE("status-triage"),
    @XmlEnumValue("status-new-info")
    STATUS_NEW_INFO("status-new-info"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    ActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionType fromValue(String v) {
        for (ActionType c: ActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
