//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{urn:ietf:params:xml:ns:iodef-1.42}MLStringType"/>
 *         &lt;element name="DateDomainWasChecked" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="RelatedDNS" type="{urn:ietf:params:xml:ns:iodef-1.42}RelatedDNSEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Nameservers" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Server" type="{urn:ietf:params:xml:ns:iodef-1.42}MLStringType"/>
 *                   &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}Address" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="SameDomainContact" type="{urn:ietf:params:xml:ns:iodef-1.42}MLStringType"/>
 *           &lt;sequence>
 *             &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}Contact" maxOccurs="unbounded"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="SystemStatus">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="spoofed"/>
 *             &lt;enumeration value="fraudulent"/>
 *             &lt;enumeration value="innocent-hacked"/>
 *             &lt;enumeration value="innocent-hijacked"/>
 *             &lt;enumeration value="unknown"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DomainStatus">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="reservedDelegation"/>
 *             &lt;enumeration value="assignedAndActive"/>
 *             &lt;enumeration value="assignedAndInactive"/>
 *             &lt;enumeration value="assignedAndOnHold"/>
 *             &lt;enumeration value="revoked"/>
 *             &lt;enumeration value="transferPending"/>
 *             &lt;enumeration value="registryLock"/>
 *             &lt;enumeration value="registrarLock"/>
 *             &lt;enumeration value="other"/>
 *             &lt;enumeration value="unknown"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "dateDomainWasChecked",
    "registrationDate",
    "expirationDate",
    "relatedDNS",
    "nameservers",
    "sameDomainContact",
    "contact"
})
@XmlRootElement(name = "DomainData")
public class DomainData {

    @XmlElement(name = "Name", required = true)
    protected MLStringType name;
    @XmlElement(name = "DateDomainWasChecked")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateDomainWasChecked;
    @XmlElement(name = "RegistrationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar registrationDate;
    @XmlElement(name = "ExpirationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(name = "RelatedDNS")
    protected List<RelatedDNSEntryType> relatedDNS;
    @XmlElement(name = "Nameservers")
    protected List<DomainData.Nameservers> nameservers;
    @XmlElement(name = "SameDomainContact")
    protected MLStringType sameDomainContact;
    @XmlElement(name = "Contact")
    protected List<Contact> contact;
    @XmlAttribute(name = "SystemStatus")
    protected String systemStatus;
    @XmlAttribute(name = "DomainStatus")
    protected String domainStatus;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setName(MLStringType value) {
        this.name = value;
    }

    /**
     * Gets the value of the dateDomainWasChecked property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateDomainWasChecked() {
        return dateDomainWasChecked;
    }

    /**
     * Sets the value of the dateDomainWasChecked property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateDomainWasChecked(XMLGregorianCalendar value) {
        this.dateDomainWasChecked = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegistrationDate(XMLGregorianCalendar value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the relatedDNS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedDNS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedDNS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedDNSEntryType }
     * 
     * 
     */
    public List<RelatedDNSEntryType> getRelatedDNS() {
        if (relatedDNS == null) {
            relatedDNS = new ArrayList<RelatedDNSEntryType>();
        }
        return this.relatedDNS;
    }

    /**
     * Gets the value of the nameservers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameservers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameservers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainData.Nameservers }
     * 
     * 
     */
    public List<DomainData.Nameservers> getNameservers() {
        if (nameservers == null) {
            nameservers = new ArrayList<DomainData.Nameservers>();
        }
        return this.nameservers;
    }

    /**
     * Gets the value of the sameDomainContact property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getSameDomainContact() {
        return sameDomainContact;
    }

    /**
     * Sets the value of the sameDomainContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setSameDomainContact(MLStringType value) {
        this.sameDomainContact = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contact }
     * 
     * 
     */
    public List<Contact> getContact() {
        if (contact == null) {
            contact = new ArrayList<Contact>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the systemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemStatus() {
        return systemStatus;
    }

    /**
     * Sets the value of the systemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemStatus(String value) {
        this.systemStatus = value;
    }

    /**
     * Gets the value of the domainStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainStatus() {
        return domainStatus;
    }

    /**
     * Sets the value of the domainStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainStatus(String value) {
        this.domainStatus = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Server" type="{urn:ietf:params:xml:ns:iodef-1.42}MLStringType"/>
     *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}Address" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "server",
        "address"
    })
    public static class Nameservers {

        @XmlElement(name = "Server", required = true)
        protected MLStringType server;
        @XmlElement(name = "Address", required = true)
        protected List<Address> address;

        /**
         * Gets the value of the server property.
         * 
         * @return
         *     possible object is
         *     {@link MLStringType }
         *     
         */
        public MLStringType getServer() {
            return server;
        }

        /**
         * Sets the value of the server property.
         * 
         * @param value
         *     allowed object is
         *     {@link MLStringType }
         *     
         */
        public void setServer(MLStringType value) {
            this.server = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the address property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Address }
         * 
         * 
         */
        public List<Address> getAddress() {
            if (address == null) {
                address = new ArrayList<Address>();
            }
            return this.address;
        }

    }

}
