//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dtype-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dtype-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="boolean"/>
 *     &lt;enumeration value="byte"/>
 *     &lt;enumeration value="character"/>
 *     &lt;enumeration value="date-time"/>
 *     &lt;enumeration value="integer"/>
 *     &lt;enumeration value="ntpstamp"/>
 *     &lt;enumeration value="portlist"/>
 *     &lt;enumeration value="real"/>
 *     &lt;enumeration value="string"/>
 *     &lt;enumeration value="file"/>
 *     &lt;enumeration value="path"/>
 *     &lt;enumeration value="frame"/>
 *     &lt;enumeration value="packet"/>
 *     &lt;enumeration value="ipv4-packet"/>
 *     &lt;enumeration value="ipv6-packet"/>
 *     &lt;enumeration value="url"/>
 *     &lt;enumeration value="csv"/>
 *     &lt;enumeration value="winreg"/>
 *     &lt;enumeration value="xml"/>
 *     &lt;enumeration value="ext-value"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dtype-type")
@XmlEnum
public enum DtypeType {

    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @XmlEnumValue("byte")
    BYTE("byte"),
    @XmlEnumValue("character")
    CHARACTER("character"),
    @XmlEnumValue("date-time")
    DATE_TIME("date-time"),
    @XmlEnumValue("integer")
    INTEGER("integer"),
    @XmlEnumValue("ntpstamp")
    NTPSTAMP("ntpstamp"),
    @XmlEnumValue("portlist")
    PORTLIST("portlist"),
    @XmlEnumValue("real")
    REAL("real"),
    @XmlEnumValue("string")
    STRING("string"),
    @XmlEnumValue("file")
    FILE("file"),
    @XmlEnumValue("path")
    PATH("path"),
    @XmlEnumValue("frame")
    FRAME("frame"),
    @XmlEnumValue("packet")
    PACKET("packet"),
    @XmlEnumValue("ipv4-packet")
    IPV_4_PACKET("ipv4-packet"),
    @XmlEnumValue("ipv6-packet")
    IPV_6_PACKET("ipv6-packet"),
    @XmlEnumValue("url")
    URL("url"),
    @XmlEnumValue("csv")
    CSV("csv"),
    @XmlEnumValue("winreg")
    WINREG("winreg"),
    @XmlEnumValue("xml")
    XML("xml"),
    @XmlEnumValue("ext-value")
    EXT_VALUE("ext-value");
    private final String value;

    DtypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DtypeType fromValue(String v) {
        for (DtypeType c: DtypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
