//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmailDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmailDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}Email" minOccurs="0"/>
 *         &lt;element name="EmailSubject" type="{urn:ietf:params:xml:ns:iodef-1.42}MLStringType" minOccurs="0"/>
 *         &lt;element name="X-Mailer" type="{urn:ietf:params:xml:ns:iodef-1.42}MLStringType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="indicator-uid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailDetails", propOrder = {
    "email",
    "emailSubject",
    "xMailer"
})
public class EmailDetails {

    @XmlElement(name = "Email")
    protected ContactMeansType email;
    @XmlElement(name = "EmailSubject")
    protected MLStringType emailSubject;
    @XmlElement(name = "X-Mailer")
    protected MLStringType xMailer;
    @XmlAttribute(name = "indicator-uid")
    protected String indicatorUid;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link ContactMeansType }
     *     
     */
    public ContactMeansType getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactMeansType }
     *     
     */
    public void setEmail(ContactMeansType value) {
        this.email = value;
    }

    /**
     * Gets the value of the emailSubject property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getEmailSubject() {
        return emailSubject;
    }

    /**
     * Sets the value of the emailSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setEmailSubject(MLStringType value) {
        this.emailSubject = value;
    }

    /**
     * Gets the value of the xMailer property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getXMailer() {
        return xMailer;
    }

    /**
     * Sets the value of the xMailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setXMailer(MLStringType value) {
        this.xMailer = value;
    }

    /**
     * Gets the value of the indicatorUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorUid() {
        return indicatorUid;
    }

    /**
     * Sets the value of the indicatorUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorUid(String value) {
        this.indicatorUid = value;
    }

}
