//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:ietf:params:xml:ns:iodef-1.42>MLStringType">
 *       &lt;attribute name="category" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="client"/>
 *             &lt;enumeration value="server-internal"/>
 *             &lt;enumeration value="server-public"/>
 *             &lt;enumeration value="www"/>
 *             &lt;enumeration value="mail"/>
 *             &lt;enumeration value="messaging"/>
 *             &lt;enumeration value="streaming"/>
 *             &lt;enumeration value="voice"/>
 *             &lt;enumeration value="file"/>
 *             &lt;enumeration value="ftp"/>
 *             &lt;enumeration value="p2p"/>
 *             &lt;enumeration value="name"/>
 *             &lt;enumeration value="directory"/>
 *             &lt;enumeration value="credential"/>
 *             &lt;enumeration value="print"/>
 *             &lt;enumeration value="application"/>
 *             &lt;enumeration value="database"/>
 *             &lt;enumeration value="infra"/>
 *             &lt;enumeration value="log"/>
 *             &lt;enumeration value="ext-value"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ext-category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="attacktype" type="{urn:ietf:params:xml:ns:iodef-1.42}att-type" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "NodeRole")
public class NodeRole
    extends MLStringType
{

    @XmlAttribute(name = "category", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String category;
    @XmlAttribute(name = "ext-category")
    protected String extCategory;
    @XmlAttribute(name = "attacktype")
    protected AttType attacktype;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the extCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtCategory() {
        return extCategory;
    }

    /**
     * Sets the value of the extCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtCategory(String value) {
        this.extCategory = value;
    }

    /**
     * Gets the value of the attacktype property.
     * 
     * @return
     *     possible object is
     *     {@link AttType }
     *     
     */
    public AttType getAttacktype() {
        return attacktype;
    }

    /**
     * Sets the value of the attacktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttType }
     *     
     */
    public void setAttacktype(AttType value) {
        this.attacktype = value;
    }

}
