//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.14 at 05:13:47 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:iodef-1.42",xmlns={
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:ietf:params:xml:ns:iodef-rid-2.0", prefix = "iodef-rid"),
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/2000/09/xmldsig#", prefix = "ds"),
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "urn:ietf:params:xml:ns:iodef-1.42", prefix = "iodef")
}, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.emc.cto.ridagent.rid.jaxb;





//elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
//elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNSET