//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReferenceName" type="{urn:ietf:params:xml:ns:iodef-1.42}MLStringType"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}URL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}Description" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="indicator-set-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="indicator-uid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="attacktype" type="{urn:ietf:params:xml:ns:iodef-1.42}att-type" />
 *       &lt;attribute name="ext-attacktype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "referenceName",
    "url",
    "description"
})
@XmlRootElement(name = "Reference")
public class Reference {

    @XmlElement(name = "ReferenceName", required = true)
    protected MLStringType referenceName;
    @XmlElement(name = "URL")
    @XmlSchemaType(name = "anyURI")
    protected List<String> url;
    @XmlElement(name = "Description")
    protected List<MLStringType> description;
    @XmlAttribute(name = "indicator-set-id")
    protected String indicatorSetId;
    @XmlAttribute(name = "indicator-uid")
    protected String indicatorUid;
    @XmlAttribute(name = "attacktype")
    protected AttType attacktype;
    @XmlAttribute(name = "ext-attacktype")
    protected String extAttacktype;

    /**
     * Gets the value of the referenceName property.
     * 
     * @return
     *     possible object is
     *     {@link MLStringType }
     *     
     */
    public MLStringType getReferenceName() {
        return referenceName;
    }

    /**
     * Sets the value of the referenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MLStringType }
     *     
     */
    public void setReferenceName(MLStringType value) {
        this.referenceName = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the url property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getURL() {
        if (url == null) {
            url = new ArrayList<String>();
        }
        return this.url;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MLStringType }
     * 
     * 
     */
    public List<MLStringType> getDescription() {
        if (description == null) {
            description = new ArrayList<MLStringType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the indicatorSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorSetId() {
        return indicatorSetId;
    }

    /**
     * Sets the value of the indicatorSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorSetId(String value) {
        this.indicatorSetId = value;
    }

    /**
     * Gets the value of the indicatorUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorUid() {
        return indicatorUid;
    }

    /**
     * Sets the value of the indicatorUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorUid(String value) {
        this.indicatorUid = value;
    }

    /**
     * Gets the value of the attacktype property.
     * 
     * @return
     *     possible object is
     *     {@link AttType }
     *     
     */
    public AttType getAttacktype() {
        return attacktype;
    }

    /**
     * Sets the value of the attacktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttType }
     *     
     */
    public void setAttacktype(AttType value) {
        this.attacktype = value;
    }

    /**
     * Gets the value of the extAttacktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtAttacktype() {
        return extAttacktype;
    }

    /**
     * Sets the value of the extAttacktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtAttacktype(String value) {
        this.extAttacktype = value;
    }

}
