//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RegistryKeyModified complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegistryKeyModified">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Key" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="KeyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="registryaction">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="add_key"/>
 *                       &lt;enumeration value="add_value"/>
 *                       &lt;enumeration value="delete_key"/>
 *                       &lt;enumeration value="delete_value"/>
 *                       &lt;enumeration value="modify_key"/>
 *                       &lt;enumeration value="modify_value"/>
 *                       &lt;enumeration value="ext-value"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="ext-category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="watchlist"/>
 *                       &lt;enumeration value="ext-value"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="ext-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="indicator-uid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="indicator-set-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegistryKeyModified", propOrder = {
    "key"
})
public class RegistryKeyModified {

    @XmlElement(name = "Key", required = true)
    protected List<RegistryKeyModified.Key> key;

    /**
     * Gets the value of the key property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the key property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegistryKeyModified.Key }
     * 
     * 
     */
    public List<RegistryKeyModified.Key> getKey() {
        if (key == null) {
            key = new ArrayList<RegistryKeyModified.Key>();
        }
        return this.key;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="KeyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="registryaction">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="add_key"/>
     *             &lt;enumeration value="add_value"/>
     *             &lt;enumeration value="delete_key"/>
     *             &lt;enumeration value="delete_value"/>
     *             &lt;enumeration value="modify_key"/>
     *             &lt;enumeration value="modify_value"/>
     *             &lt;enumeration value="ext-value"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="ext-category" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="type">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="watchlist"/>
     *             &lt;enumeration value="ext-value"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="ext-type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="indicator-uid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="indicator-set-id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "keyName",
        "value"
    })
    public static class Key {

        @XmlElement(name = "KeyName", required = true)
        protected String keyName;
        @XmlElement(name = "Value")
        protected String value;
        @XmlAttribute(name = "registryaction")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String registryaction;
        @XmlAttribute(name = "ext-category")
        protected String extCategory;
        @XmlAttribute(name = "type")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String type;
        @XmlAttribute(name = "ext-type")
        protected String extType;
        @XmlAttribute(name = "indicator-uid")
        protected String indicatorUid;
        @XmlAttribute(name = "indicator-set-id")
        protected String indicatorSetId;

        /**
         * Gets the value of the keyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKeyName() {
            return keyName;
        }

        /**
         * Sets the value of the keyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKeyName(String value) {
            this.keyName = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the registryaction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistryaction() {
            return registryaction;
        }

        /**
         * Sets the value of the registryaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistryaction(String value) {
            this.registryaction = value;
        }

        /**
         * Gets the value of the extCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtCategory() {
            return extCategory;
        }

        /**
         * Sets the value of the extCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtCategory(String value) {
            this.extCategory = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the extType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtType() {
            return extType;
        }

        /**
         * Sets the value of the extType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtType(String value) {
            this.extType = value;
        }

        /**
         * Gets the value of the indicatorUid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndicatorUid() {
            return indicatorUid;
        }

        /**
         * Sets the value of the indicatorUid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndicatorUid(String value) {
            this.indicatorUid = value;
        }

        /**
         * Gets the value of the indicatorSetId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndicatorSetId() {
            return indicatorSetId;
        }

        /**
         * Sets the value of the indicatorSetId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndicatorSetId(String value) {
            this.indicatorSetId = value;
        }

    }

}
