//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RelatedDNSEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedDNSEntryType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="RecordType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="AAAA"/>
 *             &lt;enumeration value="AFSDB"/>
 *             &lt;enumeration value="APL"/>
 *             &lt;enumeration value="AXFR"/>
 *             &lt;enumeration value="CAA"/>
 *             &lt;enumeration value="CERT"/>
 *             &lt;enumeration value="CNAME"/>
 *             &lt;enumeration value="DHCID"/>
 *             &lt;enumeration value="DLV"/>
 *             &lt;enumeration value="DNAME"/>
 *             &lt;enumeration value="DNSKEY"/>
 *             &lt;enumeration value="DS"/>
 *             &lt;enumeration value="HIP"/>
 *             &lt;enumeration value="IXFR"/>
 *             &lt;enumeration value="IPSECKEY"/>
 *             &lt;enumeration value="LOC"/>
 *             &lt;enumeration value="MX"/>
 *             &lt;enumeration value="NAPTR"/>
 *             &lt;enumeration value="NS"/>
 *             &lt;enumeration value="NSEC"/>
 *             &lt;enumeration value="NSEC3"/>
 *             &lt;enumeration value="NSEC3PARAM"/>
 *             &lt;enumeration value="OPT"/>
 *             &lt;enumeration value="PTR"/>
 *             &lt;enumeration value="RRSIG"/>
 *             &lt;enumeration value="RP"/>
 *             &lt;enumeration value="SIG"/>
 *             &lt;enumeration value="SOA"/>
 *             &lt;enumeration value="SPF"/>
 *             &lt;enumeration value="SRV"/>
 *             &lt;enumeration value="SSHFP"/>
 *             &lt;enumeration value="TA"/>
 *             &lt;enumeration value="TKEY"/>
 *             &lt;enumeration value="TLSA"/>
 *             &lt;enumeration value="TSIG"/>
 *             &lt;enumeration value="TXT"/>
 *             &lt;enumeration value="ext-value"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ext-category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedDNSEntryType", propOrder = {
    "value"
})
public class RelatedDNSEntryType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "RecordType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String recordType;
    @XmlAttribute(name = "ext-category")
    protected String extCategory;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordType(String value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the extCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtCategory() {
        return extCategory;
    }

    /**
     * Sets the value of the extCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtCategory(String value) {
        this.extCategory = value;
    }

}
