//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RIDPolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RIDPolicyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-rid-2.0}PolicyRegion" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}Node"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-rid-2.0}TrafficType" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}IncidentID" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-rid-2.0}ReportSchema" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MsgType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;enumeration value="TraceRequest"/>
 *             &lt;enumeration value="Acknowledgement"/>
 *             &lt;enumeration value="Result"/>
 *             &lt;enumeration value="InvestigationRequest"/>
 *             &lt;enumeration value="Report"/>
 *             &lt;enumeration value="Query"/>
 *             &lt;enumeration value="ext-value"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ext-MsgType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MsgDestination" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;enumeration value="RIDSystem"/>
 *             &lt;enumeration value="SourceOfIncident"/>
 *             &lt;enumeration value="ext-value"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ext-MsgDestination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="restriction" type="{urn:ietf:params:xml:ns:iodef-1.42}restriction-type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RIDPolicyType", namespace = "urn:ietf:params:xml:ns:iodef-rid-2.0", propOrder = {
    "policyRegion",
    "node",
    "trafficType",
    "incidentID",
    "reportSchema"
})
public class RIDPolicyType {

    @XmlElement(name = "PolicyRegion", required = true)
    protected List<PolicyRegion> policyRegion;
    @XmlElement(name = "Node", namespace = "urn:ietf:params:xml:ns:iodef-1.42", required = true)
    protected Node node;
    @XmlElement(name = "TrafficType", required = true)
    protected List<TrafficType> trafficType;
    @XmlElement(name = "IncidentID", namespace = "urn:ietf:params:xml:ns:iodef-1.42")
    protected IncidentIDType incidentID;
    @XmlElement(name = "ReportSchema")
    protected ReportSchemaType reportSchema;
    @XmlAttribute(name = "MsgType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String msgType;
    @XmlAttribute(name = "ext-MsgType")
    protected String extMsgType;
    @XmlAttribute(name = "MsgDestination", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String msgDestination;
    @XmlAttribute(name = "ext-MsgDestination")
    protected String extMsgDestination;
    @XmlAttribute(name = "restriction")
    protected RestrictionType restriction;

    /**
     * Gets the value of the policyRegion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyRegion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicyRegion }
     * 
     * 
     */
    public List<PolicyRegion> getPolicyRegion() {
        if (policyRegion == null) {
            policyRegion = new ArrayList<PolicyRegion>();
        }
        return this.policyRegion;
    }

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link Node }
     *     
     */
    public Node getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link Node }
     *     
     */
    public void setNode(Node value) {
        this.node = value;
    }

    /**
     * Gets the value of the trafficType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trafficType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrafficType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrafficType }
     * 
     * 
     */
    public List<TrafficType> getTrafficType() {
        if (trafficType == null) {
            trafficType = new ArrayList<TrafficType>();
        }
        return this.trafficType;
    }

    /**
     * Gets the value of the incidentID property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentIDType }
     *     
     */
    public IncidentIDType getIncidentID() {
        return incidentID;
    }

    /**
     * Sets the value of the incidentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentIDType }
     *     
     */
    public void setIncidentID(IncidentIDType value) {
        this.incidentID = value;
    }

    /**
     * Gets the value of the reportSchema property.
     * 
     * @return
     *     possible object is
     *     {@link ReportSchemaType }
     *     
     */
    public ReportSchemaType getReportSchema() {
        return reportSchema;
    }

    /**
     * Sets the value of the reportSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportSchemaType }
     *     
     */
    public void setReportSchema(ReportSchemaType value) {
        this.reportSchema = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the extMsgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtMsgType() {
        return extMsgType;
    }

    /**
     * Sets the value of the extMsgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtMsgType(String value) {
        this.extMsgType = value;
    }

    /**
     * Gets the value of the msgDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgDestination() {
        return msgDestination;
    }

    /**
     * Sets the value of the msgDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgDestination(String value) {
        this.msgDestination = value;
    }

    /**
     * Gets the value of the extMsgDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtMsgDestination() {
        return extMsgDestination;
    }

    /**
     * Sets the value of the extMsgDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtMsgDestination(String value) {
        this.extMsgDestination = value;
    }

    /**
     * Gets the value of the restriction property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictionType }
     *     
     */
    public RestrictionType getRestriction() {
        return restriction;
    }

    /**
     * Sets the value of the restriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictionType }
     *     
     */
    public void setRestriction(RestrictionType value) {
        this.restriction = value;
    }

}
