//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for RIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-rid-2.0}RIDPolicy" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-rid-2.0}RequestStatus" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-rid-2.0}IncidentSource" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}language" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RIDType", namespace = "urn:ietf:params:xml:ns:iodef-rid-2.0", propOrder = {
    "ridPolicy",
    "requestStatus",
    "incidentSource"
})
@XmlRootElement(name = "RID",namespace = "urn:ietf:params:xml:ns:iodef-rid-2.0")
public class RIDType {

    @XmlElement(name = "RIDPolicy")
    protected RIDPolicyType ridPolicy;
    @XmlElement(name = "RequestStatus")
    protected RequestStatusType requestStatus;
    @XmlElement(name = "IncidentSource")
    protected IncidentSourceType incidentSource;
    @XmlAttribute(name = "lang", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;

    /**
     * Gets the value of the ridPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link RIDPolicyType }
     *     
     */
    public RIDPolicyType getRIDPolicy() {
        return ridPolicy;
    }

    /**
     * Sets the value of the ridPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RIDPolicyType }
     *     
     */
    public void setRIDPolicy(RIDPolicyType value) {
        this.ridPolicy = value;
    }

    /**
     * Gets the value of the requestStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStatusType }
     *     
     */
    public RequestStatusType getRequestStatus() {
        return requestStatus;
    }

    /**
     * Sets the value of the requestStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStatusType }
     *     
     */
    public void setRequestStatus(RequestStatusType value) {
        this.requestStatus = value;
    }

    /**
     * Gets the value of the incidentSource property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentSourceType }
     *     
     */
    public IncidentSourceType getIncidentSource() {
        return incidentSource;
    }

    /**
     * Sets the value of the incidentSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentSourceType }
     *     
     */
    public void setIncidentSource(IncidentSourceType value) {
        this.incidentSource = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
