//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 05:36:33 PM IST 
//


package com.emc.cto.ridagent.rid.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *           &lt;element name="Portlist" type="{urn:ietf:params:xml:ns:iodef-1.42}PortlistType"/>
 *         &lt;/choice>
 *         &lt;element name="ProtoType" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ProtoCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ProtoField" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}Application" minOccurs="0"/>
 *         &lt;element name="EmailInfo" type="{urn:ietf:params:xml:ns:iodef-1.42}EmailDetails" minOccurs="0"/>
 *         &lt;element ref="{urn:ietf:params:xml:ns:iodef-1.42}DomainData" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ip_protocol" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="indicator-uid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="indicator-set-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "port",
    "portlist",
    "protoType",
    "protoCode",
    "protoField",
    "application",
    "emailInfo",
    "domainData"
})
@XmlRootElement(name = "Service")
public class Service {

    @XmlElement(name = "Port")
    protected BigInteger port;
    @XmlElement(name = "Portlist")
    protected String portlist;
    @XmlElement(name = "ProtoType")
    protected BigInteger protoType;
    @XmlElement(name = "ProtoCode")
    protected BigInteger protoCode;
    @XmlElement(name = "ProtoField")
    protected BigInteger protoField;
    @XmlElement(name = "Application")
    protected SoftwareType application;
    @XmlElement(name = "EmailInfo")
    protected EmailDetails emailInfo;
    @XmlElement(name = "DomainData")
    protected List<DomainData> domainData;
    @XmlAttribute(name = "ip_protocol", required = true)
    protected BigInteger ipProtocol;
    @XmlAttribute(name = "indicator-uid")
    protected String indicatorUid;
    @XmlAttribute(name = "indicator-set-id")
    protected String indicatorSetId;

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPort(BigInteger value) {
        this.port = value;
    }

    /**
     * Gets the value of the portlist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortlist() {
        return portlist;
    }

    /**
     * Sets the value of the portlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortlist(String value) {
        this.portlist = value;
    }

    /**
     * Gets the value of the protoType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProtoType() {
        return protoType;
    }

    /**
     * Sets the value of the protoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProtoType(BigInteger value) {
        this.protoType = value;
    }

    /**
     * Gets the value of the protoCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProtoCode() {
        return protoCode;
    }

    /**
     * Sets the value of the protoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProtoCode(BigInteger value) {
        this.protoCode = value;
    }

    /**
     * Gets the value of the protoField property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProtoField() {
        return protoField;
    }

    /**
     * Sets the value of the protoField property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProtoField(BigInteger value) {
        this.protoField = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareType }
     *     
     */
    public SoftwareType getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareType }
     *     
     */
    public void setApplication(SoftwareType value) {
        this.application = value;
    }

    /**
     * Gets the value of the emailInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EmailDetails }
     *     
     */
    public EmailDetails getEmailInfo() {
        return emailInfo;
    }

    /**
     * Sets the value of the emailInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailDetails }
     *     
     */
    public void setEmailInfo(EmailDetails value) {
        this.emailInfo = value;
    }

    /**
     * Gets the value of the domainData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainData }
     * 
     * 
     */
    public List<DomainData> getDomainData() {
        if (domainData == null) {
            domainData = new ArrayList<DomainData>();
        }
        return this.domainData;
    }

    /**
     * Gets the value of the ipProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIpProtocol() {
        return ipProtocol;
    }

    /**
     * Sets the value of the ipProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIpProtocol(BigInteger value) {
        this.ipProtocol = value;
    }

    /**
     * Gets the value of the indicatorUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorUid() {
        return indicatorUid;
    }

    /**
     * Sets the value of the indicatorUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorUid(String value) {
        this.indicatorUid = value;
    }

    /**
     * Gets the value of the indicatorSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorSetId() {
        return indicatorSetId;
    }

    /**
     * Sets the value of the indicatorSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorSetId(String value) {
        this.indicatorSetId = value;
    }

}
